import { Router } from 'express';
import { mongoDb } from '../db/mongodb.ts';
import { requireAuth, requireRole } from '../auth/middleware.ts';
import { createAuditLog } from '../db/repositories.ts';
import type { Offer, WishlistItem, Notification } from '../models/catalog.ts';
import type { Product, Shop, User } from '../models/domain.ts';

export const features = Router();

const normalize = (value: unknown) => typeof value === 'string' ? value.trim() : '';
const typoScore = (a: string, b: string) => { if (!a || !b) return 0; if (a.includes(b) || b.includes(a)) return 0.9; let i=0,j=0,miss=0; while(i<a.length&&j<b.length){if(a[i]===b[j]){i++;j++;}else{miss++;i++;}} return j===b.length ? Math.max(0,1-miss/Math.max(a.length,1)) : 0; };

features.get('/search', async (req,res) => {
  const db=mongoDb(); if(!db) return res.json([]);
  const q=normalize(req.query.q).toLowerCase(); const category=normalize(req.query.category); const shopId=normalize(req.query.shopId);
  const filter: Record<string,unknown>={active:true,...(category?{category}:{}),...(shopId?{shopId}:{})};
  const products=await db.collection<Product>('products').find(filter).limit(500).toArray();
  if(!q) return res.json(products.slice(0,50));
  return res.json(products.map(p=>({...p,_score:typoScore(p.name.toLowerCase(),q)})).filter(p=>p._score>=0.45).sort((a,b)=>b._score-a._score).slice(0,50));
});

features.use(requireAuth);
features.get('/wishlist', requireRole('customer'), async(req,res)=>{const db=mongoDb();if(!db)return res.json([]);const ids=await db.collection<WishlistItem>('wishlist').find({userId:req.user!.id}).toArray();const products=await db.collection<Product>('products').find({id:{$in:ids.map(x=>x.productId)},active:true}).toArray();return res.json(products);});
features.post('/wishlist/:productId', requireRole('customer'), async(req,res)=>{const db=mongoDb();if(!db)return res.status(503).json({error:'MongoDB is required for wishlist persistence'});const product=await db.collection<Product>('products').findOne({id:req.params.productId,active:true});if(!product)return res.status(404).json({error:'Product not found'});const existing=await db.collection<WishlistItem>('wishlist').findOne({userId:req.user!.id,productId:product.id});if(existing){await db.collection('wishlist').deleteOne({userId:req.user!.id,productId:product.id});return res.json({liked:false});}await db.collection<WishlistItem>('wishlist').insertOne({userId:req.user!.id,productId:product.id,createdAt:new Date().toISOString()});return res.status(201).json({liked:true});});

features.get('/offers', async(_req,res)=>{const db=mongoDb();if(!db)return res.json([]);const now=new Date().toISOString();return res.json(await db.collection<Offer>('offers').find({active:true,startsAt:{$lte:now},endsAt:{$gte:now}}).sort({minOrderValue:1}).toArray());});
features.post('/offers', requireRole('shopkeeper','store_manager','admin','super_admin'), async(req,res)=>{const db=mongoDb();if(!db)return res.status(503).json({error:'MongoDB is required for offers'});const code=normalize(req.body?.code).toUpperCase();const title=normalize(req.body?.title);const discountType=req.body?.discountType;const discountValue=Number(req.body?.discountValue);const minOrderValue=Number(req.body?.minOrderValue??0);const startsAt=normalize(req.body?.startsAt)||new Date().toISOString();const endsAt=normalize(req.body?.endsAt);if(!code||!title||!['PERCENT','FLAT'].includes(discountType)||!Number.isFinite(discountValue)||discountValue<=0||!Number.isFinite(minOrderValue)||minOrderValue<0||!endsAt||new Date(endsAt)<=new Date(startsAt))return res.status(400).json({error:'Invalid offer details'});if(discountType==='PERCENT'&&discountValue>100)return res.status(400).json({error:'Percentage discount cannot exceed 100'});const offer:Offer={id:`offer-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,code,title,description:normalize(req.body?.description),discountType,discountValue,minOrderValue,maxDiscount:Number.isFinite(Number(req.body?.maxDiscount))?Number(req.body.maxDiscount):undefined,active:true,startsAt,endsAt};await db.collection<Offer>('offers').insertOne(offer);await createAuditLog({id:`audit-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,actorId:req.user!.id,actorRole:req.user!.role,action:'CREATE_OFFER',entity:'offer',entityId:offer.id,createdAt:new Date().toISOString()});return res.status(201).json(offer);});

features.patch('/offers/:id', requireRole('shopkeeper','store_manager','admin','super_admin'), async(req,res)=>{const db=mongoDb();if(!db)return res.status(503).json({error:'MongoDB is required for offers'});const active=Boolean(req.body?.active);const updated=await db.collection<Offer>('offers').findOneAndUpdate({id:req.params.id},{$set:{active}},{returnDocument:'after'});if(!updated)return res.status(404).json({error:'Offer not found'});await createAuditLog({id:`audit-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,actorId:req.user!.id,actorRole:req.user!.role,action:'UPDATE_OFFER',entity:'offer',entityId:updated.id,metadata:{active},createdAt:new Date().toISOString()});return res.json(updated);});

features.get('/shops/:shopId/settings', async(req,res)=>{const db=mongoDb();if(!db)return res.json({operatingHours:{},delivery:{freeDeliveryMinimum:499,deliveryFee:39}});const settings=await db.collection('shopSettings').findOne({shopId:req.params.shopId});return res.json(settings??{shopId:req.params.shopId,operatingHours:{},delivery:{freeDeliveryMinimum:499,deliveryFee:39}});});
features.put('/shops/:shopId/settings', requireRole('shopkeeper','store_manager','admin','super_admin'), async(req,res)=>{const db=mongoDb();if(!db)return res.status(503).json({error:'MongoDB is required for shop settings'});if(!['admin','super_admin'].includes(req.user!.role)&&req.user!.shopId!==req.params.shopId)return res.status(403).json({error:'Shop access denied'});const operatingHours=typeof req.body?.operatingHours==='object'?req.body.operatingHours:{};const delivery=typeof req.body?.delivery==='object'?req.body.delivery:{};const freeDeliveryMinimum=Number(delivery.freeDeliveryMinimum??499),deliveryFee=Number(delivery.deliveryFee??39);if(!Number.isFinite(freeDeliveryMinimum)||freeDeliveryMinimum<0||!Number.isFinite(deliveryFee)||deliveryFee<0)return res.status(400).json({error:'Invalid delivery settings'});const settings={shopId:req.params.shopId,operatingHours,delivery:{freeDeliveryMinimum,deliveryFee},updatedAt:new Date().toISOString(),updatedBy:req.user!.id};await db.collection('shopSettings').updateOne({shopId:req.params.shopId},{$set:settings},{upsert:true});await createAuditLog({id:`audit-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,actorId:req.user!.id,actorRole:req.user!.role,action:'UPDATE_SHOP_SETTINGS',entity:'shop',entityId:req.params.shopId,metadata:{operatingHours,delivery},createdAt:new Date().toISOString()});return res.json(settings);});

features.post('/products/bulk', requireRole('shopkeeper','store_manager','admin','super_admin'), async(req,res)=>{const db=mongoDb();if(!db)return res.status(503).json({error:'MongoDB is required for bulk product upload'});const rows=Array.isArray(req.body?.products)?req.body.products:[];if(!rows.length||rows.length>5000)return res.status(400).json({error:'Upload between 1 and 5000 products'});const shopId=['admin','super_admin'].includes(req.user!.role)?normalize(req.body?.shopId):req.user!.shopId;if(!shopId)return res.status(400).json({error:'Shop ID is required'});const docs=rows.map((r:any)=>({id:normalize(r.id)||`p-${Date.now()}-${Math.random().toString(36).slice(2,9)}`,sku:normalize(r.sku),name:normalize(r.name),category:normalize(r.category)||'Pantry',unit:normalize(r.unit)||'unit',mrp:Number(r.mrp),sellingPrice:Number(r.sellingPrice),costPrice:Number(r.costPrice??r.sellingPrice),stock:Math.max(0,Math.round(Number(r.stock)||0)),minStock:Math.max(0,Math.round(Number(r.minStock)||5)),shopId,imageUrl:normalize(r.imageUrl)||undefined,active:true}));if(docs.some(d=>!d.sku||!d.name||!Number.isFinite(d.mrp)||!Number.isFinite(d.sellingPrice)||d.sellingPrice<0||d.mrp<0))return res.status(400).json({error:'Each product needs sku, name, mrp and valid prices'});await db.collection<Product>('products').bulkWrite(docs.map(d=>({updateOne:{filter:{sku:d.sku,shopId},update:{$set:d},upsert:true}})));await createAuditLog({id:`audit-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,actorId:req.user!.id,actorRole:req.user!.role,action:'BULK_PRODUCT_UPLOAD',entity:'product',metadata:{shopId,rowCount:docs.length},createdAt:new Date().toISOString()});return res.status(201).json({count:docs.length,shopId});});

features.get('/admin/audit-logs', requireRole('admin','super_admin'), async(req,res)=>{const db=mongoDb();if(!db)return res.json([]);return res.json(await db.collection('auditLogs').find({}).sort({createdAt:-1}).limit(500).toArray());});
features.get('/admin/customers', requireRole('admin','super_admin'), async(_req,res)=>{const db=mongoDb();if(!db)return res.json([]);return res.json(await db.collection<User>('users').find({role:'customer'}).project({passwordHash:0}).sort({name:1}).limit(5000).toArray());});
features.get('/admin/system-settings', requireRole('admin','super_admin'), async(req,res)=>{const db=mongoDb();if(!db)return res.json({});return res.json(await db.collection('systemSettings').findOne({id:'global'})??{id:'global'});});
features.put('/admin/system-settings', requireRole('admin','super_admin'), async(req,res)=>{const db=mongoDb();if(!db)return res.status(503).json({error:'MongoDB is required for system settings'});const settings={id:'global',...req.body,updatedAt:new Date().toISOString(),updatedBy:req.user!.id};delete (settings as any).password;await db.collection('systemSettings').updateOne({id:'global'},{$set:settings},{upsert:true});await createAuditLog({id:`audit-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,actorId:req.user!.id,actorRole:req.user!.role,action:'UPDATE_SYSTEM_SETTINGS',entity:'system',entityId:'global',createdAt:new Date().toISOString()});return res.json(settings);});

features.get('/admin/shops/:shopId/customers', requireRole('admin','super_admin'), async(req,res)=>{const db=mongoDb();if(!db)return res.json([]);const orders=await db.collection('orders').find({shopId:req.params.shopId}).project({customerId:1}).toArray();const ids=[...new Set(orders.map(o=>o.customerId))];return res.json(await db.collection<User>('users').find({id:{$in:ids},role:'customer'}).project({passwordHash:0}).toArray());});

features.post('/proof-of-delivery', requireRole('employee'), async(req,res)=>{const db=mongoDb();if(!db)return res.status(503).json({error:'MongoDB is required for proof of delivery'});const orderId=normalize(req.body?.orderId),proofUrl=normalize(req.body?.proofUrl),note=normalize(req.body?.note);if(!orderId||!proofUrl)return res.status(400).json({error:'orderId and proofUrl are required'});const assignment=await db.collection('deliveryAssignments').findOne({orderId,employeeId:req.user!.id});if(!assignment)return res.status(403).json({error:'Delivery is not assigned to you'});const proof={id:`pod-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,orderId,employeeId:req.user!.id,proofUrl,note,createdAt:new Date().toISOString()};await db.collection('proofOfDelivery').insertOne(proof);await createAuditLog({id:`audit-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,actorId:req.user!.id,actorRole:req.user!.role,action:'PROOF_OF_DELIVERY',entity:'order',entityId:orderId,createdAt:new Date().toISOString()});return res.status(201).json(proof);});
