import { useEffect, useState, type ReactNode } from 'react';
import { CheckCircle2, IndianRupee, MapPin, PackageCheck, RefreshCw, Truck, TrendingUp } from 'lucide-react';
import { api, type ApiDeliveryQueueItem, type ApiNotification, type ApiUser, type DeliveryPricing, type DeliveryStatus } from '../services/api';

type Props = { admin?: boolean; flash: (message: string) => void };
const steps: DeliveryStatus[] = ['ASSIGNED', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED'];
const next: Partial<Record<DeliveryStatus, DeliveryStatus>> = { ASSIGNED: 'PICKED_UP', PICKED_UP: 'OUT_FOR_DELIVERY', OUT_FOR_DELIVERY: 'DELIVERED' };
const inputClass='w-full rounded-xl border border-white/10 bg-white/10 px-3 py-2.5 text-sm text-white outline-none placeholder:text-white/40 focus:border-white/30';

export function DeliveryDashboard({ admin = false, flash }: Props) {
  const [orders, setOrders] = useState<ApiDeliveryQueueItem[]>([]);
  const [employees, setEmployees] = useState<ApiUser[]>([]);
  const [notifications, setNotifications] = useState<ApiNotification[]>([]);
  const [earnings, setEarnings] = useState<{completedDeliveries:number;totalDistanceKm:number;totalEarnings:number;currentRatePerKm:number;entries:{orderId:string;distanceKm:number;ratePerKm:number;earning:number;deliveredAt?:string}[]}>({completedDeliveries:0,totalDistanceKm:0,totalEarnings:0,currentRatePerKm:5,entries:[]});
  const [pricing, setPricing] = useState<DeliveryPricing>({baseRatePerKm:5,milestoneRatePerKm:7,milestoneDeliveries:50,updatedAt:'',updatedBy:''});
  const [busy, setBusy] = useState<string | null>(null);
  const [selectedEmployee, setSelectedEmployee] = useState<Record<string, string>>({});
  const [distance, setDistance] = useState<Record<string, string>>({});
  const [editPricing, setEditPricing] = useState({baseRatePerKm:'5',milestoneRatePerKm:'7',milestoneDeliveries:'50'});

  const load = async () => {
    try {
      const queue = await api.deliveryQueue(); setOrders(queue);
      if (admin) { const [staff,p] = await Promise.all([api.deliveryEmployees(), api.deliveryPricing()]); setEmployees(staff); setPricing(p); setEditPricing({baseRatePerKm:String(p.baseRatePerKm),milestoneRatePerKm:String(p.milestoneRatePerKm),milestoneDeliveries:String(p.milestoneDeliveries)}); }
      else { const [e,n] = await Promise.all([api.deliveryEarnings(), api.notifications()]); setEarnings(e); setNotifications(n); }
    } catch (error) { flash(error instanceof Error ? error.message : 'Unable to load delivery workspace'); }
  };
  useEffect(() => { void load(); const timer=window.setInterval(()=>void load(), admin?30000:10000); return ()=>window.clearInterval(timer); }, [admin]);

  const assign = async (orderId: string) => { const employeeId=selectedEmployee[orderId]; const km=Number(distance[orderId]); if(!employeeId)return flash('Choose a delivery employee first'); if(!Number.isFinite(km)||km<=0)return flash('Enter a valid delivery distance in kilometres'); setBusy(orderId); try{await api.assignDelivery(orderId,employeeId,km);await load();flash('Delivery assigned — employee notified');}catch(error){flash(error instanceof Error?error.message:'Assignment failed')}finally{setBusy(null)} };
  const advance = async (order: ApiDeliveryQueueItem) => { const currentStatus=order.deliveryStatus??(order.status==='OUT_FOR_DELIVERY'?'OUT_FOR_DELIVERY':'ASSIGNED'); const target=next[currentStatus]; if(!target)return; setBusy(order.id); try{await api.deliveryStatus(order.id,target);await load();flash(`${order.id} → ${target.replaceAll('_',' ')}`)}catch(error){flash(error instanceof Error?error.message:'Delivery update failed')}finally{setBusy(null)} };
  const savePricing = async () => { const base=Number(editPricing.baseRatePerKm), milestone=Number(editPricing.milestoneRatePerKm), count=Number(editPricing.milestoneDeliveries); if(![base,milestone,count].every(Number.isFinite)||base<=0||milestone<=0||count<1)return flash('Enter valid delivery pricing values'); setBusy('pricing'); try{const p=await api.updateDeliveryPricing({baseRatePerKm:base,milestoneRatePerKm:milestone,milestoneDeliveries:Math.round(count)});setPricing(p);flash('Delivery pricing updated');}catch(error){flash(error instanceof Error?error.message:'Unable to update pricing')}finally{setBusy(null)} };

  return <main className="mx-auto max-w-[1500px] px-4 py-7 sm:px-6 lg:px-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#819087]">{admin ? 'Admin / Dispatch' : 'Employee / Delivery'}</p><h1 className="heading mt-1 text-3xl font-extrabold text-[#173d2e]">{admin ? 'Delivery control & pay' : 'Delivery control'}</h1><p className="mt-1 text-sm text-[#74837a]">{admin ? 'Dispatch parcels and control the live delivery pay rules.' : 'Assignments, fast alerts and precise delivery earnings.'}</p></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-2xl bg-[#173d2e] px-4 py-3 text-sm font-extrabold text-white"><RefreshCw size={16}/>Refresh</button></div>
    {!admin && <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Kpi icon={<Truck/>} label="Deliveries" value={String(earnings.completedDeliveries)} sub="completed"/><Kpi icon={<MapPin/>} label="Distance" value={`${earnings.totalDistanceKm.toFixed(1)} km`} sub="completed distance"/><Kpi icon={<IndianRupee/>} label="Total income" value={`₹${earnings.totalEarnings.toFixed(2)}`} sub="delivery earnings"/><Kpi icon={<TrendingUp/>} label="Current rate" value={`₹${earnings.currentRatePerKm}/km`} sub={`after ${pricing.milestoneDeliveries} deliveries`} /></section>}
    {!admin && <section className="mt-5 rounded-3xl bg-[#173d2e] p-5 text-white shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-extrabold">Your earnings</h2><p className="mt-1 text-xs text-white/65">₹{pricing.baseRatePerKm}/km normally • ₹{pricing.milestoneRatePerKm}/km after {pricing.milestoneDeliveries} completed deliveries.</p></div><IndianRupee size={22}/></div><div className="mt-4 max-h-72 space-y-2 overflow-y-auto">{earnings.entries.map(item=><div key={item.orderId} className="flex items-center justify-between rounded-2xl bg-white/10 p-3 text-xs"><div><b>{item.orderId}</b><div className="mt-1 text-white/60">{item.distanceKm.toFixed(1)} km × ₹{item.ratePerKm}/km{item.deliveredAt?` • ${new Date(item.deliveredAt).toLocaleDateString('en-IN')}`:''}</div></div><strong>₹{item.earning.toFixed(2)}</strong></div>)}{!earnings.entries.length&&<div className="py-8 text-center text-white/55">No completed delivery earnings yet.</div>}</div></section>}
    {!admin && <section className="mt-5 rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="heading text-xl font-extrabold text-[#173d2e]">New delivery alerts</h2><p className="mt-1 text-xs text-[#7d8c83]">This list refreshes every 10 seconds while you are on the delivery portal.</p></div><PackageCheck className="text-[#5d836b]" size={20}/></div><div className="mt-4 space-y-2">{notifications.slice(0,6).map(n=><div key={n.id} className={`rounded-2xl p-4 ${n.read?'bg-[#fafbf8]':'bg-[#edf7ef]'}`}><div className="flex justify-between gap-3"><b className="text-sm text-[#203229]">{n.title}</b><span className="text-[10px] text-[#7d8c83]">{new Date(n.createdAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</span></div><p className="mt-1 text-xs leading-5 text-[#718078]">{n.message}</p></div>)}{!notifications.length&&<div className="py-8 text-center text-sm text-[#7d8c83]">No new delivery notifications.</div>}</div></section>}
    {admin && <section className="mt-7 rounded-3xl bg-[#173d2e] p-5 text-white shadow-sm"><div className="flex items-center gap-2"><IndianRupee size={20}/><h2 className="font-extrabold">Delivery pay settings</h2></div><p className="mt-1 text-xs text-white/65">You control the rates used for future delivery assignments.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><label><span className="mb-1 block text-[10px] font-extrabold uppercase tracking-wide text-white/60">Standard ₹ / km</span><input className={inputClass} value={editPricing.baseRatePerKm} onChange={e=>setEditPricing(v=>({...v,baseRatePerKm:e.target.value}))}/></label><label><span className="mb-1 block text-[10px] font-extrabold uppercase tracking-wide text-white/60">Milestone ₹ / km</span><input className={inputClass} value={editPricing.milestoneRatePerKm} onChange={e=>setEditPricing(v=>({...v,milestoneRatePerKm:e.target.value}))}/></label><label><span className="mb-1 block text-[10px] font-extrabold uppercase tracking-wide text-white/60">Milestone deliveries</span><input className={inputClass} value={editPricing.milestoneDeliveries} onChange={e=>setEditPricing(v=>({...v,milestoneDeliveries:e.target.value}))}/></label></div><button onClick={()=>void savePricing()} disabled={busy==='pricing'} className="mt-4 rounded-xl bg-[#d7ef8d] px-4 py-2.5 text-xs font-extrabold text-[#173d2e] disabled:opacity-50">{busy==='pricing'?'Saving…':'Save pay settings'}</button><p className="mt-2 text-[10px] text-white/45">Current: ₹{pricing.baseRatePerKm}/km • ₹{pricing.milestoneRatePerKm}/km after {pricing.milestoneDeliveries} completed deliveries.</p></section>}
    <section className="mt-7 rounded-3xl bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-2"><MapPin className="text-[#5d836b]" size={20}/><h2 className="heading text-xl font-extrabold text-[#173d2e]">Delivery queue</h2></div><div className="mt-4 space-y-3">{orders.map(order=>{const currentStatus=order.deliveryStatus??(order.status==='OUT_FOR_DELIVERY'?'OUT_FOR_DELIVERY':'ASSIGNED');const current=steps.indexOf(currentStatus);const target=next[currentStatus];return <div key={order.id} className="rounded-2xl border border-black/5 bg-[#fafbf8] p-4"><div className="flex flex-wrap items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#eaf1ea] text-[#3c7358]"><PackageCheck size={18}/></div><div className="min-w-[190px] flex-1"><div className="text-sm font-extrabold text-[#203229]">{order.id}</div><div className="mt-1 text-xs text-[#7d8b83]">{order.items.reduce((s,i)=>s+i.quantity,0)} items • ₹{order.total}{order.distanceKm?` • ${order.distanceKm} km`:''}</div></div>{order.earning!==undefined&&<span className="rounded-full bg-[#eaf6df] px-3 py-1 text-[10px] font-extrabold text-[#47715a]">₹{order.earning.toFixed(2)}</span>}<span className="rounded-full bg-[#edf3ee] px-3 py-1 text-[10px] font-extrabold uppercase tracking-wider text-[#47715a]">{currentStatus.replaceAll('_',' ')}</span>{target&&<button disabled={busy===order.id} onClick={()=>void advance(order)} className="rounded-xl bg-[#173d2e] px-3 py-2 text-xs font-extrabold text-white disabled:opacity-50">{busy===order.id?'Updating…':target==='DELIVERED'?'Mark delivered':target.replaceAll('_',' ')}</button>}</div><div className="mt-4 flex gap-1">{steps.map((step,index)=><div key={step} className={`h-1.5 flex-1 rounded-full ${index<=current?'bg-[#5d836b]':'bg-[#e6ebe6'}`}/>)}</div>{admin&&!order.deliveryEmployeeId&&order.status==='READY'&&<div className="mt-4 grid gap-2 sm:grid-cols-[1fr_160px_auto]"><select value={selectedEmployee[order.id]??''} onChange={e=>setSelectedEmployee(v=>({...v,[order.id]:e.target.value}))} className="rounded-xl border border-black/10 bg-white px-3 py-2 text-xs font-semibold"><option value="">Assign employee…</option>{employees.map(employee=><option key={employee.id} value={employee.id}>{employee.name} • {employee.phone}</option>)}</select><input inputMode="decimal" placeholder="Distance km" value={distance[order.id]??''} onChange={e=>setDistance(v=>({...v,[order.id]:e.target.value}))} className="rounded-xl border border-black/10 bg-white px-3 py-2 text-xs font-semibold"/><button disabled={busy===order.id} onClick={()=>void assign(order.id)} className="rounded-xl bg-[#eaf1ea] px-4 py-2 text-xs font-extrabold text-[#315245]">Assign & notify</button></div>}</div>})}{!orders.length&&<div className="py-12 text-center text-sm text-[#7d8c83]">No delivery orders in the queue.</div>}</div></section>
  </main>;
}
function Kpi({icon,label,value,sub}:{icon:ReactNode;label:string;value:string;sub:string}){return <div className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#eaf1ea] text-[#3c7358]">{icon}</div><div className="mt-4 text-xs font-bold text-[#7d8c83]">{label}</div><div className="mt-1 text-2xl font-extrabold text-[#173d2e]">{value}</div><div className="mt-1 text-xs text-[#8a968f]">{sub}</div></div>;}
