import { useEffect, useMemo, useState } from 'react';
import { KeyRound, RefreshCw, Store, UserRound, X, Copy, CheckCircle2 } from 'lucide-react';

type Kind = 'shopkeeper' | 'employee';
type Credential = { slot:number; loginId:string; password:string; assignedToId?:string; assignedAt?:string; active:boolean };
type Shop = { id:string; name:string; address:string; active:boolean };
type Application = { referenceId:string; type:Kind; fullName:string; businessName?:string; status:string; activatedAt?:string; };

async function adminRequest<T>(path:string, options:RequestInit={}):Promise<T>{
  const token=localStorage.getItem('freshcart_token');
  const headers=new Headers(options.headers); headers.set('Content-Type','application/json'); if(token)headers.set('Authorization',`Bearer ${token}`);
  const response=await fetch(`/api${path}`,{...options,headers});
  if(!response.ok){const body=await response.json().catch(()=>null) as {error?:string}|null; throw new Error(body?.error||`Request failed (${response.status})`);}
  return response.json() as Promise<T>;
}

export function PartnerCredentialManager(){
  const [open,setOpen]=useState(false); const [kind,setKind]=useState<Kind>('shopkeeper'); const [credentials,setCredentials]=useState<Credential[]>([]); const [shops,setShops]=useState<Shop[]>([]); const [applications,setApplications]=useState<Application[]>([]);
  const [suffix,setSuffix]=useState(''); const [referenceId,setReferenceId]=useState(''); const [shopId,setShopId]=useState(''); const [assigned,setAssigned]=useState<{loginId:string;password:string;slot:number}|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [copied,setCopied]=useState('');
  const load=async(nextKind:Kind=kind)=>{setError(''); try{const [pool,storeList,appList]=await Promise.all([adminRequest<{credentials:Credential[]}>(`/admin/partner-credentials?kind=${nextKind}`),adminRequest<Shop[]>('/admin/shops'),adminRequest<Application[]>(`/admin/onboarding/applications?type=${nextKind}&status=APPROVED`)]);setCredentials(pool.credentials);setShops(storeList);setApplications(appList.filter(a=>!a.activatedAt));}catch(err){setError(err instanceof Error?err.message:'Unable to load credentials');}};
  useEffect(()=>{if(open)void load();},[open]); useEffect(()=>{if(open)void load(kind);},[kind]);
  const available=useMemo(()=>credentials.filter(c=>!c.assignedToId&&c.active),[credentials]);
  const assign=async()=>{if(!/^\d{1,4}$/.test(suffix.trim())||!referenceId.trim()||(kind==='shopkeeper'&&!shopId)){setError(kind==='shopkeeper'?'Enter application, four-digit credential and shop.':'Enter application reference and four-digit credential.');return;}setBusy(true);setError('');setAssigned(null);try{const result=await adminRequest<{credentials:{loginId:string;password:string;slot:number}}>(`/admin/onboarding/applications/${referenceId.trim()}/assign-credential`,{method:'POST',body:JSON.stringify({suffix:suffix.trim(),...(shopId?{shopId}: {})})});setAssigned(result.credentials);setSuffix('');setReferenceId('');setShopId('');await load(kind);}catch(err){setError(err instanceof Error?err.message:'Unable to assign credential');}finally{setBusy(false);}};
  const copy=async(label:string,value:string)=>{try{await navigator.clipboard.writeText(value);setCopied(label);window.setTimeout(()=>setCopied(''),1200);}catch{setError('Clipboard access is unavailable.');}};
  if(!open)return <button onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-40 inline-flex items-center gap-2 rounded-2xl bg-[#173d2e] px-4 py-3 text-xs font-extrabold text-white shadow-xl hover:bg-[#24523e]"><KeyRound size={16}/>Partner Credentials</button>;
  return <div className="fixed inset-0 z-50 bg-[#173d2e]/45 p-3 backdrop-blur-sm sm:p-6"><div className="mx-auto flex h-full max-w-6xl flex-col overflow-hidden rounded-3xl bg-[#f7f7f2] shadow-2xl">
    <div className="flex items-center justify-between border-b border-black/5 bg-white px-5 py-4 sm:px-7"><div><div className="flex items-center gap-2 text-[#4c8b67]"><KeyRound size={18}/><span className="text-[10px] font-extrabold uppercase tracking-[.18em]">Owner credential control</span></div><h2 className="mt-1 text-xl font-extrabold text-[#173d2e]">100 unique portal credentials</h2><p className="mt-1 text-xs text-[#74837a]">Use the last four digits to assign a credential to an approved shopkeeper or employee.</p></div><button onClick={()=>setOpen(false)} className="rounded-full p-2 text-[#64756c] hover:bg-[#edf2ed]"><X size={19}/></button></div>
    <div className="flex-1 overflow-y-auto p-5 sm:p-7">
      <div className="grid gap-5 lg:grid-cols-[370px_1fr]">
        <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex gap-2"><button onClick={()=>setKind('shopkeeper')} className={`flex-1 rounded-xl px-3 py-2.5 text-xs font-extrabold ${kind==='shopkeeper'?'bg-[#173d2e] text-white':'bg-[#eef3ed] text-[#567063]'}`}><Store size={14} className="mr-1 inline"/>Shopkeeper</button><button onClick={()=>setKind('employee')} className={`flex-1 rounded-xl px-3 py-2.5 text-xs font-extrabold ${kind==='employee'?'bg-[#173d2e] text-white':'bg-[#eef3ed] text-[#567063]'}`}><UserRound size={14} className="mr-1 inline"/>Employee</button></div>
          <div className="mt-5 space-y-3"><label className="block"><span className="mb-1.5 block text-[10px] font-extrabold uppercase tracking-wide text-[#68776f]">Approved application</span><select value={referenceId} onChange={e=>setReferenceId(e.target.value)} className="w-full rounded-xl border border-black/10 bg-[#fafbf8] px-3 py-3 text-sm"><option value="">Select application…</option>{applications.map(a=><option key={a.referenceId} value={a.referenceId}>{a.referenceId} — {a.fullName}{a.businessName?` — ${a.businessName}`:''}</option>)}</select></label>
            {kind==='shopkeeper'&&<label className="block"><span className="mb-1.5 block text-[10px] font-extrabold uppercase tracking-wide text-[#68776f]">Assign shop</span><select value={shopId} onChange={e=>setShopId(e.target.value)} className="w-full rounded-xl border border-black/10 bg-[#fafbf8] px-3 py-3 text-sm"><option value="">Select shop…</option>{shops.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name} — {s.id}</option>)}</select></label>}
            <label className="block"><span className="mb-1.5 block text-[10px] font-extrabold uppercase tracking-wide text-[#68776f]">Last four digits</span><input inputMode="numeric" maxLength={4} value={suffix} onChange={e=>setSuffix(e.target.value.replace(/\D/g,'').slice(0,4))} placeholder="0001 → 0100" className="w-full rounded-xl border border-black/10 bg-[#fafbf8] px-3 py-3 text-lg font-extrabold tracking-[.25em]" /></label>
            <div className="rounded-2xl bg-[#f1f6ef] p-3 text-xs leading-5 text-[#62736a]">{kind==='shopkeeper'?<>Login IDs are <b>FC-SHOP-0001</b> through <b>FC-SHOP-0100</b>.</>:<>Employee IDs are <b>FC-EMP-0001</b> through <b>FC-EMP-0100</b>.</>}</div>
            <button disabled={busy} onClick={()=>void assign()} className="w-full rounded-xl bg-[#173d2e] px-4 py-3 text-sm font-extrabold text-white disabled:opacity-50">{busy?'Assigning…':'Assign credential'}</button>
            {error&&<div className="rounded-xl bg-[#fff0ed] px-3 py-2 text-xs font-semibold text-[#a14335]">{error}</div>}
            {assigned&&<div className="rounded-2xl border border-[#cfe2d2] bg-[#eef8f0] p-4"><div className="flex items-center gap-2 text-xs font-extrabold text-[#287348]"><CheckCircle2 size={16}/>Assigned successfully</div><div className="mt-3 space-y-2 text-sm"><div className="flex items-center justify-between gap-2"><span className="text-[#6b796f]">Login ID</span><button onClick={()=>void copy('id',assigned.loginId)} className="font-extrabold text-[#173d2e]">{assigned.loginId} <Copy size={13} className="inline ml-1"/></button></div><div className="flex items-center justify-between gap-2"><span className="text-[#6b796f]">Password</span><button onClick={()=>void copy('pass',assigned.password)} className="font-extrabold text-[#173d2e]">{assigned.password} <Copy size={13} className="inline ml-1"/></button></div></div>{copied&&<div className="mt-2 text-[10px] font-bold text-[#4c8b67]">Copied</div>}<p className="mt-3 text-[10px] leading-4 text-[#65766d]">Send these credentials securely to the approved applicant. Do not publish them in the public repository.</p></div>}
          </div></section>
        <section className="rounded-3xl bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h3 className="font-extrabold text-[#173d2e]">Credential pool</h3><p className="mt-1 text-xs text-[#7d8c83]">{available.length} available • {credentials.length-available.length} assigned</p></div><button onClick={()=>void load(kind)} className="rounded-xl bg-[#eef3ed] p-2 text-[#4f715c]"><RefreshCw size={16}/></button></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{credentials.map(c=><button key={c.slot} onClick={()=>!c.assignedToId&&setSuffix(String(c.slot).padStart(4,'0'))} className={`rounded-xl border p-3 text-left ${c.assignedToId?'border-black/5 bg-[#f0f2ee] opacity-60':'border-[#dce6dd] bg-[#fafcf9] hover:border-[#8fb99a] hover:bg-[#f2f7f1]'}`}><div className="text-[10px] font-extrabold text-[#7b8981]">{String(c.slot).padStart(4,'0')}</div><div className="mt-1 text-xs font-extrabold text-[#315b43]">{c.loginId}</div><div className={`mt-1 text-[9px] font-bold ${c.assignedToId?'text-[#9a6a61]':'text-[#4c8b67]'}`}>{c.assignedToId?'ASSIGNED':'AVAILABLE'}</div></button>)}</div></section>
      </div>
    </div>
  </div></div>;
}
