import type { ClientSession, Filter, UpdateFilter } from 'mongodb';
import type { Order, Product, User, Shop } from '../models/domain';
import type { Address, DeliverySlot, Payment, DeliveryAssignment, Notification, Attendance, AuditLog } from '../models/catalog';
import { mongoClient, mongoDb } from './mongodb.ts';

export async function findUser(identifier: string, role: string) { const db = mongoDb(); return db ? db.collection<User>('users').findOne({ $or: [{ email: identifier }, { phone: identifier }, { username: identifier }], role, active: true }) : null; }
export async function findUserById(id: string) { const db = mongoDb(); return db ? db.collection<User>('users').findOne({ id, active: true }, { projection: { passwordHash: 0 } }) : null; }
export async function createUser(user: User) { const db = mongoDb(); if (!db) return; await db.collection<User>('users').insertOne(user); }
export async function listProducts(shopId?: string, category?: string, q?: string) { const db = mongoDb(); if (!db) return []; const filter: Filter<Product> = { active: true, ...(shopId ? { shopId } : {}), ...(category ? { category } : {}) }; if (q) filter.$text = { $search: q }; return db.collection<Product>('products').find(filter).toArray(); }
export async function listShops() { const db = mongoDb(); return db ? db.collection<Shop>('shops').find({ active: true }).toArray() : []; }
export async function listStaff(shopId?: string) { const db = mongoDb(); if (!db) return []; return db.collection<User>('users').find({ active: true, role: { $in: ['employee', 'shopkeeper', 'store_manager'] }, ...(shopId ? { shopId } : {}) }).project({ passwordHash: 0 }).toArray(); }
export async function listAddresses(userId: string) { const db = mongoDb(); return db ? db.collection<Address>('addresses').find({ userId }).sort({ isDefault: -1 }).toArray() : []; }
export async function insertAddress(address: Address) { const db = mongoDb(); if (!db) return; if (address.isDefault) await db.collection<Address>('addresses').updateMany({ userId: address.userId }, { $set: { isDefault: false } }); await db.collection<Address>('addresses').insertOne(address); }
export async function listDeliverySlots() { const db = mongoDb(); return db ? db.collection<DeliverySlot>('deliverySlots').find({ active: true, $expr: { $lt: ['$booked', '$capacity'] } }).sort({ date: 1, startTime: 1 }).toArray() : []; }
export async function reserveProductsAndSlot(shopId: string, items: Array<{ productId: string; quantity: number }>, slotId: string) { const db = mongoDb(); if (!db) return { products: [], slot: null }; const products: Product[] = []; for (const item of items) { const result = await db.collection<Product>('products').findOneAndUpdate({ id: item.productId, shopId, active: true, stock: { $gte: item.quantity } }, { $inc: { stock: -item.quantity } } as UpdateFilter<Product>, { returnDocument: 'after' }); if (!result) { for (const reserved of items.slice(0, products.length)) await db.collection<Product>('products').updateOne({ id: reserved.productId, shopId }, { $inc: { stock: reserved.quantity } }); return { products: [], slot: null }; } products.push(result); } const slot = await db.collection<DeliverySlot>('deliverySlots').findOneAndUpdate({ id: slotId, active: true, $expr: { $lt: ['$booked', '$capacity'] } }, { $inc: { booked: 1 } }, { returnDocument: 'after' }); if (!slot) { for (const item of items) await db.collection<Product>('products').updateOne({ id: item.productId, shopId }, { $inc: { stock: item.quantity } }); return { products: [], slot: null }; } return { products, slot }; }

export async function createOrderTransaction(order: Order, payment: Payment, items: Array<{ productId: string; quantity: number }>, slotId: string) { const db = mongoDb(); const client = mongoClient(); if (!db || !client) throw new Error('MongoDB is not connected'); const session = client.startSession(); try { let result: { order: Order; payment: Payment; slot: DeliverySlot } | null = null; await session.withTransaction(async () => { for (const item of items) { const updated = await db.collection<Product>('products').findOneAndUpdate({ id: item.productId, shopId: order.shopId, active: true, stock: { $gte: item.quantity } }, { $inc: { stock: -item.quantity } } as UpdateFilter<Product>, { returnDocument: 'after', session }); if (!updated) throw new Error('One or more products became unavailable'); } const slot = await db.collection<DeliverySlot>('deliverySlots').findOneAndUpdate({ id: slotId, active: true, $expr: { $lt: ['$booked', '$capacity'] } }, { $inc: { booked: 1 } }, { returnDocument: 'after', session }); if (!slot) throw new Error('Delivery slot became unavailable'); await db.collection<Order>('orders').insertOne(order, { session }); await db.collection<Payment>('payments').insertOne(payment, { session }); result = { order, payment, slot }; }); if (!result) throw new Error('Order transaction failed'); return result; } finally { await session.endSession(); } }
export async function cancelOrderTransaction(order: Order, payment?: Payment) { const db = mongoDb(); const client = mongoClient(); if (!db || !client) throw new Error('MongoDB is not connected'); const session = client.startSession(); try { let result: Order | null = null; await session.withTransaction(async () => { const updated = await db.collection<Order>('orders').findOneAndUpdate({ id: order.id, status: { $in: ['PLACED', 'ACCEPTED'] } }, { $set: { status: 'CANCELLED' } }, { returnDocument: 'after', session }); if (!updated) throw new Error('Order can no longer be cancelled'); for (const item of order.items) await db.collection<Product>('products').updateOne({ id: item.productId, shopId: order.shopId }, { $inc: { stock: item.quantity } }, { session }); if (order.deliverySlotId) await db.collection<DeliverySlot>('deliverySlots').updateOne({ id: order.deliverySlotId, booked: { $gt: 0 } }, { $inc: { booked: -1 } }, { session }); if (payment) await db.collection<Payment>('payments').updateOne({ id: payment.id }, { $set: { status: payment.method === 'COD' ? 'CANCELLED' : 'REFUND_PENDING' } as never }, { session }); result = updated; }); if (!result) throw new Error('Cancellation failed'); return result; } finally { await session.endSession(); } }
export async function insertOrder(order: Order) { const db = mongoDb(); if (db) await db.collection<Order>('orders').insertOne(order); }
export async function insertPayment(payment: Payment) { const db = mongoDb(); if (db) await db.collection<Payment>('payments').insertOne(payment); }
export async function findOrders(filter: Filter<Order> = {}) { const db = mongoDb(); return db ? db.collection<Order>('orders').find(filter).sort({ createdAt: -1 }).toArray() : []; }
const ORDER_TRANSITIONS: Record<Order['status'], readonly Order['status'][]> = { PLACED: ['ACCEPTED', 'CANCELLED'], ACCEPTED: ['PICKING', 'CANCELLED'], PICKING: ['PACKING'], PACKING: ['READY'], READY: ['OUT_FOR_DELIVERY'], OUT_FOR_DELIVERY: ['DELIVERED'], DELIVERED: [], CANCELLED: [] };
const ORDER_MESSAGES: Record<Order['status'], string> = { PLACED: 'Your order has been placed.', ACCEPTED: 'The shop has accepted your order.', PICKING: 'Your order is being picked.', PACKING: 'Your order is being packed.', READY: 'Your order is ready.', OUT_FOR_DELIVERY: 'Your order is out for delivery.', DELIVERED: 'Your order has been delivered.', CANCELLED: 'Your order has been cancelled.' };
async function notifyOrderTransition(order: Order, status: Order['status']) { const db = mongoDb(); if (!db) return; const now = new Date().toISOString(); const recipients = new Set<string>([order.customerId]); const shop = await db.collection<Shop>('shops').findOne({ id: order.shopId }); if (shop?.shopkeeperId) recipients.add(shop.shopkeeperId); const staff = await db.collection<User>('users').find({ shopId: order.shopId, role: { $in: ['employee', 'store_manager'] }, active: true }).project({ id: 1 }).limit(100).toArray(); for (const user of staff) recipients.add(user.id); await db.collection<Notification>('notifications').insertMany([...recipients].map(userId => ({ id: `notif-${Date.now()}-${Math.random().toString(36).slice(2,8)}-${userId}`, userId, title: `Order ${order.id}: ${status.replaceAll('_',' ')}`, message: ORDER_MESSAGES[status], type: 'ORDER', read: false, createdAt: now }))); }
export async function updateOrderStatus(orderId: string, status: Order['status']) { const db = mongoDb(); if (!db) return null; const current = await db.collection<Order>('orders').findOne({ id: orderId }); if (!current) return null; if (current.status === status) return current; if (!ORDER_TRANSITIONS[current.status].includes(status)) throw new Error(`Invalid order status transition: ${current.status} -> ${status}`); const updated = await db.collection<Order>('orders').findOneAndUpdate({ id: orderId, status: current.status }, { $set: { status, updatedAt: new Date().toISOString() } }, { returnDocument: 'after' }); if (updated) { await notifyOrderTransition(updated, status); await createAuditLog({ id: `audit-${Date.now()}-${Math.random().toString(36).slice(2,8)}`, actorId: 'system', actorRole: 'system', action: `ORDER_STATUS_${status}`, entity: 'order', entityId: updated.id, metadata: { from: current.status, to: status, shopId: updated.shopId }, createdAt: new Date().toISOString() }); } return updated; }
export async function updateStock(productId: string, stock: number, shopId?: string) { const db = mongoDb(); return db ? db.collection<Product>('products').findOneAndUpdate({ id: productId, ...(shopId ? { shopId } : {}) }, { $set: { stock } }, { returnDocument: 'after' }) : null; }
export async function listDeliveryAssignments(filter: Filter<DeliveryAssignment> = {}) { const db = mongoDb(); return db ? db.collection<DeliveryAssignment>('deliveryAssignments').find(filter).sort({ assignedAt: -1 }).toArray() : []; }
export async function upsertDeliveryAssignment(assignment: DeliveryAssignment) { const db = mongoDb(); if (db) await db.collection<DeliveryAssignment>('deliveryAssignments').updateOne({ orderId: assignment.orderId }, { $set: assignment }, { upsert: true }); }
export async function listNotifications(userId: string) { const db = mongoDb(); return db ? db.collection<Notification>('notifications').find({ userId }).sort({ createdAt: -1 }).limit(100).toArray() : []; }
export async function createNotification(notification: Notification) { const db = mongoDb(); if (db) await db.collection<Notification>('notifications').insertOne(notification); }
export async function markNotificationRead(notificationId: string, userId: string) { const db = mongoDb(); return db ? db.collection<Notification>('notifications').findOneAndUpdate({ id: notificationId, userId }, { $set: { read: true } }, { returnDocument: 'after' }) : null; }
export async function listAttendance(userId: string, from?: string, to?: string) { const db = mongoDb(); if (!db) return []; const filter: Filter<Attendance> = { userId, ...(from || to ? { date: { ...(from ? { $gte: from } : {}), ...(to ? { $lte: to } : {}) } } : {}) }; return db.collection<Attendance>('attendance').find(filter).sort({ date: -1 }).toArray(); }
export async function upsertAttendance(attendance: Attendance) { const db = mongoDb(); if (db) await db.collection<Attendance>('attendance').updateOne({ userId: attendance.userId, date: attendance.date }, { $set: attendance }, { upsert: true }); }
export async function createAuditLog(log: AuditLog) { const db = mongoDb(); if (db) await db.collection<AuditLog>('auditLogs').insertOne(log); }
